name: Setup Node.js Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js. Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm --version

      - run: node --version
